mysite/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('home/', views.index, name='index'),
    path('archive/', views.archive, name='archive'),
    path('<int:blog_id>/', views.entry, name='entry'),
    path('about/', views.about, name='about'),
    path('post/', views.post, name='post'),
    path('comment/', views.comment, name='comment'),
    path('techtips+css/', views.techWithCSS, name='techWithCSS'),
    path('techtips-css/', views.techWithoutCSS, name='techWithoutCSS'),
    path('plan', views.plan, name='plan')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

mysite/blog/models.py
from django.db import models


class VisitorLog(models.Model):
    when = models.CharField(max_length=128, default=0)
    who = models.CharField(max_length=128)


class Blog(models.Model):
    title = models.CharField(max_length=128, default="title")
    author = models.CharField(max_length=128, default="author")
    content = models.TextField(max_length=10000, default="content")
    posted = models.CharField(max_length=128)
    commentNumber = models.CharField(max_length=128, default="0")


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    commenter = models.CharField(max_length=128, default="commenter")
    email = models.EmailField(max_length=128, default="email@email.com")
    content = models.TextField(max_length=10000, default="content")
    posted = models.CharField(max_length=128)

mysite/blog/forms.py
from django import forms


class BlogForm(forms.Form):
    title = forms.CharField(label="title", max_length=128)
    author = forms.CharField(label="author", max_length=128)
    content = forms.CharField(label="content", max_length=10000)


class CommentForm(forms.Form):
    blog = forms.CharField(label="blog", max_length=128)
    commenter = forms.CharField(label="commenter", max_length=128)
    email = forms.CharField(label="email", max_length=128)
    content = forms.CharField(label="content", max_length=10000)

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import VisitorLog, Blog, Comment
from datetime import datetime
from django.views.decorators.csrf import csrf_exempt
from .forms import BlogForm, CommentForm


def index(request):
    visitor = VisitorLog()
    dateString = datetime.now()
    dateString = dateString.strftime("%Y-%m-%d %H:%M:%S")
    visitor.when = dateString
    visitor.who = request.META['REMOTE_ADDR']
    visitor.save()
    visits = list(VisitorLog.objects.all())
    visitsLen = len(visits)
    if len(visits) > 10:
        visits = visits[-10:]

    blogPost = list(Blog.objects.all())[-3:]
    blogPost.reverse()
    context = {'visits': visits,
               'visitsLen': visitsLen,
               'blogPost': blogPost}

    return render(request, 'blog/index.html', context)


@csrf_exempt
def post(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        newPost = Blog()
        dateString = datetime.now()
        dateString = dateString.strftime("%Y-%m-%d %H:%M:%S")
        if form.is_valid():
            title = form.cleaned_data['title']
            author = form.cleaned_data['author']
            content = form.cleaned_data['content']
            newPost.title = title
            newPost.author = author
            newPost.content = content
            newPost.posted = dateString
            newPost.commentNumber = "0"
        newPost.save()

        visitor = VisitorLog()
        dateString = datetime.now()
        dateString = dateString.strftime("%Y-%m-%d %H:%M:%S")
        visitor.when = dateString
        visitor.who = request.META['REMOTE_ADDR']
        visitor.save()
        visits = list(VisitorLog.objects.all())
        visitsLen = len(visits)
        if len(visits) > 10:
            visits = visits[-10:]

        blogPost = list(Blog.objects.all())[-3:]
        blogPost.reverse()
        context = {'visits': visits,
                   'visitsLen': visitsLen,
                   'blogPost': blogPost}

        return render(request, 'blog/index.html', context)


@csrf_exempt
def comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        for i in form:
            print(i)
        newComment = Comment()
        dateString = datetime.now()
        dateString = dateString.strftime("%Y-%m-%d %H:%M:%S")
        blog_id = None
        if form.is_valid():
            commenter = form.cleaned_data['commenter']
            email = form.cleaned_data['email']
            content = form.cleaned_data['content']
            blog_id = int(form.cleaned_data['blog'])
            newComment.blog = Blog.objects.get(pk=blog_id)
            print(newComment.blog)
            print(blog_id)
            newComment.commenter = commenter
            newComment.email = email
            newComment.content = content
            newComment.posted = dateString
        newComment.save()

    blogEntry = get_object_or_404(Blog, pk=blog_id)
    commentAdder = int(blogEntry.commentNumber)
    commentAdder += 1
    blogEntry.commentNumber = str(commentAdder)
    blogEntry.save()
    commentEntry = list(Comment.objects.filter(blog=blog_id))
    commentEntry.reverse()
    context = {'blogEntry': blogEntry,
               'commentEntry': commentEntry}

    return render(request, 'blog/entry.html', context)


def about(request):
    visitor = VisitorLog()
    dateString = datetime.now()
    dateString = dateString.strftime("%Y-%m-%d %H:%M:%S")
    visitor.when = dateString
    visitor.who = request.META['REMOTE_ADDR']
    visitor.save()
    visits = list(VisitorLog.objects.all())
    visitsLen = len(visits)
    if len(visits) > 10:
        visits = visits[-10:]
    context = {'visits': visits,
               'visitsLen': visitsLen}

    return render(request, 'blog/about.html', context)


def techWithCSS(request):
    visitor = VisitorLog()
    dateString = datetime.now()
    dateString = dateString.strftime("%Y-%m-%d %H:%M:%S")
    visitor.when = dateString
    visitor.who = request.META['REMOTE_ADDR']
    visitor.save()
    visits = list(VisitorLog.objects.all())
    visitsLen = len(visits)
    if len(visits) > 10:
        visits = visits[-10:]
    context = {'visits': visits,
               'visitsLen': visitsLen}

    return render(request, 'blog/techtips+css.html', context)


def techWithoutCSS(request):
    visitor = VisitorLog()
    dateString = datetime.now()
    dateString = dateString.strftime("%Y-%m-%d %H:%M:%S")
    visitor.when = dateString
    visitor.who = request.META['REMOTE_ADDR']
    visitor.save()
    visits = list(VisitorLog.objects.all())
    visitsLen = len(visits)
    if len(visits) > 10:
        visits = visits[-10:]
    context = {'visits': visits,
               'visitsLen': visitsLen}

    return render(request, 'blog/techtips-css.html', context)


def archive(request):
    visitor = VisitorLog()
    dateString = datetime.now()
    dateString = dateString.strftime("%Y-%m-%d %H:%M:%S")
    visitor.when = dateString
    visitor.who = request.META['REMOTE_ADDR']
    visitor.save()
    visits = list(VisitorLog.objects.all())
    visitsLen = len(visits)
    if len(visits) > 10:
        visits = visits[-10:]

    blogPost = list(Blog.objects.all())
    blogPost.reverse()
    context = {'visits': visits,
               'visitsLen': visitsLen,
               'blogPost': blogPost}

    return render(request, 'blog/archive.html', context)


def entry(request, blog_id):
    blogEntry = get_object_or_404(Blog, pk=blog_id)
    commentEntry = list(Comment.objects.filter(blog=blog_id))
    commentEntry.reverse()
    visitor = VisitorLog()
    dateString = datetime.now()
    dateString = dateString.strftime("%Y-%m-%d %H:%M:%S")
    visitor.when = dateString
    visitor.who = request.META['REMOTE_ADDR']
    visitor.save()
    visits = list(VisitorLog.objects.all())
    visitsLen = len(visits)
    if len(visits) > 10:
        visits = visits[-10:]

    context = {'blogEntry': blogEntry,
               'commentEntry': commentEntry,
               'visits': visits,
               'visitsLen': visitsLen}

    return render(request, 'blog/entry.html', context)


def plan(request):
    visitor = VisitorLog()
    dateString = datetime.now()
    dateString = dateString.strftime("%Y-%m-%d %H:%M:%S")
    visitor.when = dateString
    visitor.who = request.META['REMOTE_ADDR']
    visitor.save()
    visits = list(VisitorLog.objects.all())
    visitsLen = len(visits)
    if len(visits) > 10:
        visits = visits[-10:]

    context = {'visits': visits,
               'visitsLen': visitsLen,}
    return render(request, 'blog/plan.html', context)

mysite/blog/templates/blog/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<!-- HEADER -->
<head>
    <meta charset="UTF-8">
    <title>About Bertolli</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>


<!-- BODY -->
<body>

    <h1 id="titleFont">About Bertolli</h1>

    <!-- COMMON TABLE OF CONTENTS -->
    <div>
    <h3 class="tableFont"><u>Table of Contents</u></h3>
    <ol id="tableOfContents">
        <li class="tableColor"><a href="{% url 'blog:index' %}">Bertolli's Blog</a></li>
        <li class="tableColor"><a href="{% url 'blog:about' %}">About Bertolli</a></li>
        <li class="tableColor"><a href="{% url 'blog:techWithCSS' %}">Tech Tips with CSS</a></li>
        <li class="tableColor"><a href="{% url 'blog:techWithoutCSS' %}">Tech Tips without CSS</a></li>
        <li class="tableColor">This site has been visited {{visitsLen}} time{{visits | pluralize}}</li>
    </ol>
    <br>
    </div>


    <!-- ### FIRST PICTURE/POST ###-->
    <div>
    <h2>Biography of Bertolli</h2>
    <img src="../../static/blog/images/BertolliPortrait.jpg"
         alt="Portrait of Bertolli Chuckwagon"
         title="Picture of Bertolli taken at her home in Dublin"/>

    <p><strong>Bertolli Marsha "Chip" Chuckwagon</strong>, usually referred to simply as "Bert", is a world-class
    author and critic. She is known most prominently for her work as the main editor for the famous "Odyssey" by Homer.
    The first known record of Bert is thought to be a famous cave painting found outside of Berlin. Carbon dating puts
    this drawing to somewhere around 4000 BCE. Bert is thought to be immortal, due also to the fact that "Odyssey" was
    written in the 8th century BCE. This is also thought to be true because of her numerous world records, which include
    "Most Times Survived Jumping Off The Burj Khalifa Unaided and Surviving." In more recent years, she has chosen to
    settle down from these wild adventures, and now resides in a small cottage outside of Dublin, Ireland.</p>
    <br>
    </div>


    <!-- ### SECOND PICTURE/POST ###-->
    <div>
    <h2>Adrenaline Junkie</h2>
    <img src="../../static/blog/images/BertolliSkydiving.jpg"
         alt="Bertolli skydiving at an old age"
         title="Bertolli on her 1000th skydive"/>

    <p>Despite the appearance of her old age, Bert is still quite capable of doing amazing feats. One of her proudest
    and most notable skydiving accomplishments was being the first person to do so without a parachute. From an
    interview earlier this year, she says it also happen on the first ever flight by the Wright brothers. <q><em>I had
    just fallen asleep on the wings of the first plane they ever made,</em></q> Bertolli is quoted saying, <q><em>when
    suddenly it took off. I was able to hold on until we made it about 100 feet in the air when I lost my grip. But
    since I'm an immortal being from the shadow realm, I easily survived the fall.</em></q> Bert is also the first
    known person to summit Mount Everest from base camp without the assistance of oxygen, twice in the same day. She
    also claims to know exactly where Amelia Earhart flew to and retired, but wants to keep that to herself.</p>
    <br>
    </div>


    <!-- ### THIRD PICTURE/POST ###-->
    <div>
    <h2>Author Extraordinaire</h2>
    <img src="../../static/blog/images/BertolliWriting.jpg"
         alt="Bertolli writing a book on her laptop"
         title="Bertolli working on the 10th book in her 'Death and Fire' series"/>

    <p>From a very young age, which no one knows exactly when that was, Bertolli had a passion for writing. She credits
    a lot of her ideas from the large amount of dark things she sees from the shadow realm. Much of her time is now
    spent either meditating, or writing down her visions. Her series "Death and Fire", is about to get its tenth
    installment in the spring of 2022. With over 250 million copies sold, it's the best-selling series of all time.
    Bertolli says you can expect at least ten more books in the series.</p>
    <br>
    </div>

    <!-- ### TEST DATABASE SECTION FOR VISITORS ### -->
    {% if visits %}
    <div>
    <h2>List of  Time of Visit and Visitor's IP Address</h2>
    <ol>
        {% for visitor in visits %}
            <li>{{visitor.when}} - {{visitor.who}}</li>
        {% endfor %}
    </ol>
    </div>
    {% endif %}

</body>
</html>

mysite/blog/templates/blog/archive.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<!-- HEADER -->
<head>
    <meta charset="UTF-8">
    <title>Bertolli's Blog</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>


<!-- BODY -->
<body>

    <h1 id="titleFont">Bertolli's Blog</h1>

    <!-- COMMON TABLE OF CONTENTS -->
    <div>
    <h3 class="tableFont"><u>Table of Contents</u></h3>
    <ol id="tableOfContents">
        <li class="tableColor"><a href="{% url 'blog:index' %}">Bertolli's Blog</a></li>
        <li class="tableColor"><a href="{% url 'blog:about' %}">About Bertolli</a></li>
        <li class="tableColor"><a href="{% url 'blog:techWithCSS' %}">Tech Tips with CSS</a></li>
        <li class="tableColor"><a href="{% url 'blog:techWithoutCSS' %}">Tech Tips without CSS</a></li>
        <li class="tableColor">This site has been visited {{visitsLen}} time{{visits | pluralize}}</li>
    </ol>
    <br>
    </div>

    <div id="blogList">
        <hr />
        <p>
            <a href="{% url 'blog:index' %}">Blog Home (3 Most Recent Posts)</a> - - - - -
            <a href="{% url 'blog:archive' %}">Blog Archive (All Posts)</a>
        </p>
        <hr />
    </div>
    <br>

    <!-- BLOG POST SECTION -->
    {% if blogPost %}
        {% for blogPost in blogPost %}
            <div>
                <h1>{{blogPost.title}}</h1>
                <h2>Written by {{blogPost.author}} on {{blogPost.posted}}</h2>
                <p>{{blogPost.content | truncatewords:100}}...
                    <a href="{% url 'blog:entry' blogPost.id %}">(View Full Post)</a>
                </p>
                <p>{{blogPost.commentNumber}} comments</p>
            </div>
            <br>
            <br>
        {% endfor %}
    {% else %}
        <p>No blog posts are available</p>
    {% endif %}


    <!-- ### DATABASE SECTION FOR VISITORS ### -->
    {% if visits %}
    <div>
    <h2>List of Last {{visits | length }} Visitor{{visits | pluralize}} Time and IP Address</h2>
    <ol>
        {% for visitor in visits %}
            <li>{{visitor.when}} - {{visitor.who}}</li>
        {% endfor %}
    </ol>
    </div>
    {% endif %}

</body>
</html>

mysite/blog/templates/blog/entry.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<!-- HEADER -->
<head>
    <meta charset="UTF-8">
    <title>Bertolli's Blog</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>


<!-- BODY -->
<body>

    <h1 id="titleFont">Bertolli's Blog</h1>

    <!-- COMMON TABLE OF CONTENTS -->
    <div>
    <h3 class="tableFont"><u>Table of Contents</u></h3>
    <ol id="tableOfContents">
        <li class="tableColor"><a href="{% url 'blog:index' %}">Bertolli's Blog</a></li>
        <li class="tableColor"><a href="{% url 'blog:about' %}">About Bertolli</a></li>
        <li class="tableColor"><a href="{% url 'blog:techWithCSS' %}">Tech Tips with CSS</a></li>
        <li class="tableColor"><a href="{% url 'blog:techWithoutCSS' %}">Tech Tips without CSS</a></li>
        <li class="tableColor">This site has been visited {{visitsLen}} time{{visits | pluralize}}</li>
    </ol>
    <br>
    </div>

    <div id="blogList">
        <hr />
        <p>
            <a href="{% url 'blog:index' %}">Blog Home (3 Most Recent Posts)</a> - - - - -
            <a href="{% url 'blog:archive' %}">Blog Archive (All Posts)</a>
        </p>
        <hr />
    </div>
    <br>

    <!-- BLOG POST SECTION -->
    <div>
        <h1>{{blogEntry.title}}</h1>
        <h2>Written by {{blogEntry.author}} on {{blogEntry.posted}}</h2>
        <p>{{blogEntry.content}}</p>
    </div>
    <br>

    <!-- POSTED COMMENT SECTION -->
    <div>
        <h2>Comments</h2>
    </div>
    <br>

    {% if commentEntry %}
    <div class="comment">
        {% for commentEntry in commentEntry %}
            <h3>{{commentEntry.commenter}} ({{commentEntry.email}}) on {{commentEntry.posted}}</h3>
            <p>{{commentEntry.content}}</p>
            <br>
        {% endfor %}
    </div>
    {% else %}
    <div>
        <p>No Comments Exits Yet. Be the First!</p>
    </div>
    {% endif %}

    <!-- NEW COMMENT SECTION -->
    <div>
        <form action="http://localhost:8000/blog/comment/" method="POST">
            <header>
                <h2>Create your own comment</h2>
            </header>
            <div>
                <label for="blog">Comment on {{blogEntry.title}}</label>
                <input type="hidden" id="blog" name="blog" value={{blogEntry.id}}>
            </div>
            <div>
                <label for="commenter">Name</label>
                <input id="commenter" name="commenter" value="commenter" maxlength="128" >
            </div>
            <div>
                <label for="email">Email</label>
                <input id="email" name="email" value="email@email.com" maxlength="128">
            </div>
            <div>
                <textarea id="content" name="content" rows="5" cols="120" maxlength="10000">Your comment here</textarea>
            </div>
            <div>
                <button type="submit">Submit</button>
            </div>
        </form>
    </div>
    <br>


</body>
</html>

mysite/blog/templates/blog/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<!-- HEADER -->
<head>
    <meta charset="UTF-8">
    <title>Bertolli's Blog</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>


<!-- BODY -->
<body>

    <h1 id="titleFont">Bertolli's Blog</h1>

    <!-- COMMON TABLE OF CONTENTS -->
    <div>
    <h3 class="tableFont"><u>Table of Contents</u></h3>
    <ol id="tableOfContents">
        <li class="tableColor"><a href="{% url 'blog:index' %}">Bertolli's Blog</a></li>
        <li class="tableColor"><a href="{% url 'blog:about' %}">About Bertolli</a></li>
        <li class="tableColor"><a href="{% url 'blog:techWithCSS' %}">Tech Tips with CSS</a></li>
        <li class="tableColor"><a href="{% url 'blog:techWithoutCSS' %}">Tech Tips without CSS</a></li>
        <li class="tableColor">This site has been visited {{visitsLen}} time{{visits | pluralize}}</li>
    </ol>
    <br>
    </div>

    <div id="blogList">
        <hr />
        <p>
            <a href="{% url 'blog:index' %}">Blog Home (3 Most Recent Posts)</a> - - - - -
            <a href="{% url 'blog:archive' %}">Blog Archive (All Posts)</a>
        </p>
        <hr />
    </div>
    <br>

    <!-- BLOG POST SECTION -->
    {% if blogPost %}
        {% for blogPost in blogPost %}
            <div>
                <h1>{{blogPost.title}}</h1>
                <h2>Written by {{blogPost.author}} on {{blogPost.posted}}</h2>
                <p>{{blogPost.content | truncatewords:100}}...
                    <a href="{% url 'blog:entry' blogPost.id %}">(View Full Post)</a>
                </p>
                <p>{{blogPost.commentNumber}} comments</p>
            </div>
            <br>
            <br>
        {% endfor %}
    {% else %}
        <p>No blog posts are available</p>
    {% endif %}

    <!-- CREATE BLOG POST SECTION -->
    <div>
        <form action="http://localhost:8000/blog/post/" method="POST">
            <header>
                <h2>Create your own blog post</h2>
            </header>
            <div>
                <label for="title">Blog Title</label>
                <input id="title" name="title" value="Title" maxlength="128" >
            </div>
            <div>
                <label for="author">Author</label>
                <input id="author" name="author" value="Author" maxlength="128">
            </div>
            <div>
                <textarea id="content" name="content" rows="10" cols="120" maxlength="10000">Your post here</textarea>
            </div>
            <div>
                <button type="submit">Submit</button>
            </div>
        </form>
    </div>
    <br>






    <!-- ### DATABASE SECTION FOR VISITORS ### -->
    {% if visits %}
    <div>
    <h2>List of Last {{visits | length }} Visitor{{visits | pluralize}} Time and IP Address</h2>
    <ol>
        {% for visitor in visits %}
            <li>{{visitor.when}} - {{visitor.who}}</li>
        {% endfor %}
    </ol>
    </div>
    {% endif %}

</body>
</html>

mysite/blog/templates/blog/plan.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Website Plan</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>

    <!-- COMMON TABLE OF CONTENTS -->
    <div>
    <h3 class="tableFont"><u>Table of Contents</u></h3>
    <ol id="tableOfContents">
        <li class="tableColor"><a href="{% url 'blog:index' %}">Bertolli's Blog</a></li>
        <li class="tableColor"><a href="{% url 'blog:about' %}">About Bertolli</a></li>
        <li class="tableColor"><a href="{% url 'blog:techWithCSS' %}">Tech Tips with CSS</a></li>
        <li class="tableColor"><a href="{% url 'blog:techWithoutCSS' %}">Tech Tips without CSS</a></li>
        <li class="tableColor">This site has been visited {{visitsLen}} time{{visits | pluralize}}</li>
    </ol>
    <br>
    </div>

    <h2>Time Spent On Assignment</h2>
    <ul>
        <li>Oct 15th: 3 hours on plan and design</li>
        <li>Oct 16th: 8 hours on coding on main coding</li>
        <li>Oct 17th: 6 hours on finishing code and cleaning up little details</li>
    </ul>
    <br>

    <h1>Main Files to Focus On</h1>

    <h2>0002_populate.py</h2>
    <p>This one will house the database data that will come included in the assignment. It will populate the website with 4 blog posts and all its data, and a couple of comments for each blog. It will also come with 3 pre-generated IP Addresses to populate that field.</p>
    <p>I will make two methods on this page. One to populate the VisitorLog class, and one to populate the Blog and Comment classes. I will do this by using the appreg.get_model on each class. I will then create an instance of each model, and fill out the appropriate fields for it to fill with (ex: "first = Blog()" to create a new blog item, and then fill it by using things like "first.title = "). At the end, use .save() on each file. Also, call each method using migrations.RunPython in the "operations" list at the bottom of the page.</p>

    <br>
    <h2>templates/blog/HTML FILES</h2>
    <p>For the most part, these will be the same as the old .html files from the last assignment. There are some changes, obviously, to fit the Django syntax, and the new blog elements.</p>
    <p>At the top of each page, in the common table of contents section, a visitor counter will be implemented, to track how many times any of the pages have been loaded. At the bottom of the page, the last 10 visitors IP Address and time stamps will be displayed.</p>
    <p>The link URLs are also setup a little differently, to fit in with Django's format. They need to be called in the django format, and can also pass an argument through with it.</p>
    <p>The most important part of these sites will be concerning with the "forms" that it uses. These will be used to allow the user to create new posts, and have them appear on the page. These forms will link to the appropriate page (depending on if it's a blog or a comment), and must contain id's for the form.py to be able to parse the data from it.</p>
    <p>They will also use the Django formatted "for" loops to call every post, and every comment inside each post. The home page will only show the 3 most recent posts (and only the first 100 words), and the archive page will show all blog posts.</p>

    <br>
    <h2>forms.py</h2>
    <p>This page was created because it seemed necessary based on the Django documentation on how to parse data from the QuerySets that the database info is stored in.</p>
    <p>This page will look very similar to the models.py page. But instead of using models, will use forms. Since all the data that will be passed through from the website can be interpreted as strings, every form can be forms.CharField. These forms will make it very easy for views.py to be able to break down each QuerySet and return the data contained in it.</p>

    <br>
    <h2>models.py</h2>
    <p>As stated earlier, this page is very similar to forms.py. This page will be the basis for storing data in our database.</p>
    <p>There will be 3 classes created in this file, all based off of "models.Model". The first will be VisitorLog (with variables 'when' and 'who'). The second will be Blog (with variables 'title', 'author', 'content', 'posted', and 'commentNumber'.) The last one will be Comment (with variables 'blog', 'commenter', 'email', 'content', and 'posted').</p>
    <p>Just about all of those variables will be just to store the actual data. But the 'blog' part of Comment will be a foreign key, to reference to the actual blog that it is associated with.</p>

    <br>
    <h2>urls.py</h2>
    <p>This page is very simple. It defines the paths that the website will take when a URL is requested. Every method from views.py should have a reference here to tell the website where and how to get to it.</p>

    <br>
    <h2>views.py</h2>
    <p>This page is the trickiest of all of them, and works in conjuncture with each corresponding .html file to tell the web browser what to display.</p>
    <p>Every path that is called needs a view. The views I'll create will be for the home, archive, entry, about, post, comment, plan, and the two techtips pages.</p>
    <p>To me, the two most important things this page will do is to parse the information from the forms.py, and to create the context to pass onto the .html files.</p>
    <p>There will be a couple main things I'll use to achieve these goals. The first will be to get the information from the database. This can be done in two ways: either by creating a variable, and setting it to be a list of all the objects of that type (ex: visits = list(VisitorLog.objects.all())). Or to filter a specific item using the 'get_object_or_404' method and something to filter it with (ex: blogEntry = get_object_or_404(Blog, pk=blog_id).</p>
    <p>The way the website will get information from the user will be through the forms methods. They will use the information from the request.POST to build the new requested item (either a new blog or a new comment). It will use 'form.is_valid()' to verify the form. Then it will use 'form.cleaned_data['desired variable'] to extract the information from the QuerySet. It will then build the new item, just like in 0002_populate.py, and save it to the database.</p>

    <br>
    <h1>Other important pages</h1>

    <h2>mysite/urls.py</h2>
    <p>This page will be needed to tell the website how to get to each app. It will be the beginning of the URL after the "localhost:8000/" is entered. It will contain the blog.urls, the polls.urls, and the admin site.</p>

    <br>
    <h2>mysite/settings.py</h2>
    <p>Inside this page, the blog and the polls apps will need to be included in the "INSTALLED_APPS" list. They will reference the apps.py in each respective app.</p>

    <br>
    <h2>Citation for the Lorem Ipsum text</h2>
    <p>The text for my blog posts was found at <a href="https://generator.lorem-ipsum.info/">this</a> website, in the
        <q>Lorem Ipsum: when, and when not to use it</q> section.</p>

    <h2>Photo Citations</h2>
    <p>The main portrait photo was obtained from <a href="https://stock.adobe.com/sk/search/images?k=funny+old+lady">
        here</a>. Her skydiving photo is from
        <a href="https://wisconsinskydivingcenter.com/blog/skydiving-age-limit-too-old-to-skydive/">this</a> website.
        Her final "author" photo was found from this
        <a href="https://media.istockphoto.com/photos/old-lady-doesnt-understand-laptop-picture-id542304950?k=20&m=542304950&s=170667a&w=0&h=3OZfu1_dRJ6-1rFHzGb0MPTx-9PUfWyvM1Ww7l0T2Oc=">
        stock photo</a> website.</p>

    {% if visits %}
    <div>
        <h2>List of Last {{visits | length }} Visitor{{visits | pluralize}} Time and IP Address</h2>
        <ol>
            {% for visitor in visits %}
                <li>{{visitor.when}} - {{visitor.who}}</li>
            {% endfor %}
        </ol>
    </div>
    {% endif %}

</body>
</html>